[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
cache_path = "cache"
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
ffi = false
evm_version = "paris"

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = false
int_types = "long"
quote_style = "double"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
